//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gos.Services.Resources.ExportResource", typeof(ExportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorni zapis.
        /// </summary>
        public static string ConversationalForm {
            get {
                return ResourceManager.GetString("ConversationalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanal.
        /// </summary>
        public static string DiscourseChannel {
            get {
                return ResourceManager.GetString("DiscourseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip govornega dogodka.
        /// </summary>
        public static string DiscourseEvent {
            get {
                return ResourceManager.GetString("DiscourseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regija snemanja.
        /// </summary>
        public static string DiscourseRegion {
            get {
                return ResourceManager.GetString("DiscourseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vir.
        /// </summary>
        public static string DiscourseSource {
            get {
                return ResourceManager.GetString("DiscourseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip govora.
        /// </summary>
        public static string DiscourseType {
            get {
                return ResourceManager.GetString("DiscourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leto snemanja.
        /// </summary>
        public static string DiscourseYear {
            get {
                return ResourceManager.GetString("DiscourseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Število pojavitev.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levo besedilo.
        /// </summary>
        public static string LeftContext {
            get {
                return ResourceManager.GetString("LeftContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblikoslovne lastnosti standardizirane oblike.
        /// </summary>
        public static string Msd {
            get {
                return ResourceManager.GetString("Msd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desno besedilo.
        /// </summary>
        public static string RightContext {
            get {
                return ResourceManager.GetString("RightContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starost govorca.
        /// </summary>
        public static string SpeakerAge {
            get {
                return ResourceManager.GetString("SpeakerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izobrazba govorca.
        /// </summary>
        public static string SpeakerEducation {
            get {
                return ResourceManager.GetString("SpeakerEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvi jezik govorca.
        /// </summary>
        public static string SpeakerLanguage {
            get {
                return ResourceManager.GetString("SpeakerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regija govorca.
        /// </summary>
        public static string SpeakerRegion {
            get {
                return ResourceManager.GetString("SpeakerRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol govorca.
        /// </summary>
        public static string SpeakerSex {
            get {
                return ResourceManager.GetString("SpeakerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana oblika.
        /// </summary>
        public static string StandardizedForm {
            get {
                return ResourceManager.GetString("StandardizedForm", resourceCulture);
            }
        }
    }
}
