//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConcordanceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConcordanceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gos.Web.Resources.ConcordanceResource", typeof(ConcordanceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatna beseda v okolici.
        /// </summary>
        public static string AddAdditionalWordInContext {
            get {
                return ResourceManager.GetString("AddAdditionalWordInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beseda v okolici.
        /// </summary>
        public static string AddWordInContext {
            get {
                return ResourceManager.GetString("AddWordInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napredno iskanje.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korpusne oznake.
        /// </summary>
        public static string DetailsCorpusAnnotation {
            get {
                return ResourceManager.GetString("DetailsCorpusAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kanal.
        /// </summary>
        public static string DetailsDiscourseChannel {
            get {
                return ResourceManager.GetString("DetailsDiscourseChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opis dogodka.
        /// </summary>
        public static string DetailsDiscourseDescription {
            get {
                return ResourceManager.GetString("DetailsDiscourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip dogodka.
        /// </summary>
        public static string DetailsDiscourseEvent {
            get {
                return ResourceManager.GetString("DetailsDiscourseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regija snemanja.
        /// </summary>
        public static string DetailsDiscourseRegion {
            get {
                return ResourceManager.GetString("DetailsDiscourseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vir.
        /// </summary>
        public static string DetailsDiscourseSource {
            get {
                return ResourceManager.GetString("DetailsDiscourseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podatki o izjavi.
        /// </summary>
        public static string DetailsInformation {
            get {
                return ResourceManager.GetString("DetailsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to število udeležencev.
        /// </summary>
        public static string DetailsNumberOfSpeakers {
            get {
                return ResourceManager.GetString("DetailsNumberOfSpeakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Govorec.
        /// </summary>
        public static string DetailsSpeaker {
            get {
                return ResourceManager.GetString("DetailsSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starost.
        /// </summary>
        public static string DetailsSpeakerAge {
            get {
                return ResourceManager.GetString("DetailsSpeakerAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oznaka.
        /// </summary>
        public static string DetailsSpeakerCode {
            get {
                return ResourceManager.GetString("DetailsSpeakerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to izobrazba.
        /// </summary>
        public static string DetailsSpeakerEducation {
            get {
                return ResourceManager.GetString("DetailsSpeakerEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prvi jezik.
        /// </summary>
        public static string DetailsSpeakerLanguage {
            get {
                return ResourceManager.GetString("DetailsSpeakerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regija.
        /// </summary>
        public static string DetailsSpeakerRegion {
            get {
                return ResourceManager.GetString("DetailsSpeakerRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spol.
        /// </summary>
        public static string DetailsSpeakerSex {
            get {
                return ResourceManager.GetString("DetailsSpeakerSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana različica.
        /// </summary>
        public static string DetailsStandardForm {
            get {
                return ResourceManager.GetString("DetailsStandardForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beseda.
        /// </summary>
        public static string DetailsTokensConversationalForm {
            get {
                return ResourceManager.GetString("DetailsTokensConversationalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana osnovna oblika.
        /// </summary>
        public static string DetailsTokensLemma {
            get {
                return ResourceManager.GetString("DetailsTokensLemma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblikoslovne lastnosti standardizirane oblike.
        /// </summary>
        public static string DetailsTokensMsd {
            get {
                return ResourceManager.GetString("DetailsTokensMsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana oblika.
        /// </summary>
        public static string DetailsTokensStandardForm {
            get {
                return ResourceManager.GetString("DetailsTokensStandardForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddaljenost.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levo.
        /// </summary>
        public static string HistoryLeft {
            get {
                return ResourceManager.GetString("HistoryLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta.
        /// </summary>
        public static string HistoryPartOfSpeech {
            get {
                return ResourceManager.GetString("HistoryPartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desno.
        /// </summary>
        public static string HistoryRight {
            get {
                return ResourceManager.GetString("HistoryRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beseda.
        /// </summary>
        public static string HistoryWord {
            get {
                return ResourceManager.GetString("HistoryWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beseda v okolici.
        /// </summary>
        public static string HistoryWordInContext {
            get {
                return ResourceManager.GetString("HistoryWordInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oddaljenost.
        /// </summary>
        public static string HistoryWordInContextDistance {
            get {
                return ResourceManager.GetString("HistoryWordInContextDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka pred.
        /// </summary>
        public static string LeftMark {
            get {
                return ResourceManager.GetString("LeftMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brez oznake.
        /// </summary>
        public static string NoMark {
            get {
                return ResourceManager.GetString("NoMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besedna vrsta.
        /// </summary>
        public static string PartOfSpeech {
            get {
                return ResourceManager.GetString("PartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predvajaj.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predvajaj vse.
        /// </summary>
        public static string PlayAll {
            get {
                return ResourceManager.GetString("PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazujem {0}-{1} od &lt;strong&gt;{2}&lt;/strong&gt; konkordanc..
        /// </summary>
        public static string ResultsInfo {
            get {
                return ResourceManager.GetString("ResultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaka za.
        /// </summary>
        public static string RightMark {
            get {
                return ResourceManager.GetString("RightMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskana beseda.
        /// </summary>
        public static string SearchTheWord {
            get {
                return ResourceManager.GetString("SearchTheWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način iskanja.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vse oblike besed.
        /// </summary>
        public static string SearchTypeAllForms {
            get {
                return ResourceManager.GetString("SearchTypeAllForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samo vpisana oblika.
        /// </summary>
        public static string SearchTypeExactForm {
            get {
                return ResourceManager.GetString("SearchTypeExactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iskana beseda.
        /// </summary>
        public static string SearchWord {
            get {
                return ResourceManager.GetString("SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uporabljaš &lt;a class=&quot;show-help&quot; href=&quot;#&quot;&gt;enostavno iskanje&lt;/a&gt;.
        /// </summary>
        public static string SimpleSearchInUse {
            get {
                return ResourceManager.GetString("SimpleSearchInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Določi oddaljenost.
        /// </summary>
        public static string SpecifyDistance {
            get {
                return ResourceManager.GetString("SpecifyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Določi točno mesto.
        /// </summary>
        public static string SpecifyPosition {
            get {
                return ResourceManager.GetString("SpecifyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip zapisa.
        /// </summary>
        public static string SpellingType {
            get {
                return ResourceManager.GetString("SpellingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v pogovornem zapisu.
        /// </summary>
        public static string TranscriptionTypeConversational {
            get {
                return ResourceManager.GetString("TranscriptionTypeConversational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v standardiziranem zapisu.
        /// </summary>
        public static string TranscriptionTypeStandard {
            get {
                return ResourceManager.GetString("TranscriptionTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beseda.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V okolici.
        /// </summary>
        public static string WordInContext {
            get {
                return ResourceManager.GetString("WordInContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je beseda.
        /// </summary>
        public static string WordInContextIs {
            get {
                return ResourceManager.GetString("WordInContextIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ni besede.
        /// </summary>
        public static string WordInContextIsNot {
            get {
                return ResourceManager.GetString("WordInContextIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ime.
        /// </summary>
        public static string WordName {
            get {
                return ResourceManager.GetString("WordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premor.
        /// </summary>
        public static string WordPause {
            get {
                return ResourceManager.GetString("WordPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to priimek.
        /// </summary>
        public static string WordSurname {
            get {
                return ResourceManager.GetString("WordSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nerazumljivo besedilo.
        /// </summary>
        public static string WordUnclear {
            get {
                return ResourceManager.GetString("WordUnclear", resourceCulture);
            }
        }
    }
}
