//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gos.Web.Resources.ListResource", typeof(ListResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatno.
        /// </summary>
        public static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorni zapis.
        /// </summary>
        public static string ConversationalForm {
            get {
                return ResourceManager.GetString("ConversationalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Število pojavitev.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loči besede glede na oblikoslovne lastnosti.
        /// </summary>
        public static string GroupByMsd {
            get {
                return ResourceManager.GetString("GroupByMsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V meniju &lt;strong&gt;Dodatno&lt;/strong&gt; določimo besedno vrsto in druge lastnosti iskane besede..
        /// </summary>
        public static string HelpAdditional {
            get {
                return ResourceManager.GetString("HelpAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uporabljaš &lt;a class=&quot;show-help&quot; href=&quot;#&quot;&gt;iskanje po seznamih&lt;/a&gt;.
        /// </summary>
        public static string ListSearchInUse {
            get {
                return ResourceManager.GetString("ListSearchInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblikoslovne lastnosti standardizirane oblike.
        /// </summary>
        public static string Msd {
            get {
                return ResourceManager.GetString("Msd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besedna vrsta.
        /// </summary>
        public static string PartOfSpeech {
            get {
                return ResourceManager.GetString("PartOfSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazujem {0}-{1} od &lt;strong&gt;{2}&lt;/strong&gt; besed..
        /// </summary>
        public static string ResultsInfo {
            get {
                return ResourceManager.GetString("ResultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorni zapis (A-Ž).
        /// </summary>
        public static string SortConversationalAsc {
            get {
                return ResourceManager.GetString("SortConversationalAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorni zapis (Ž-A).
        /// </summary>
        public static string SortConversationalDesc {
            get {
                return ResourceManager.GetString("SortConversationalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Število pojavitev (naraščajoče).
        /// </summary>
        public static string SortFrequencyAsc {
            get {
                return ResourceManager.GetString("SortFrequencyAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Število pojavitev (padajoče).
        /// </summary>
        public static string SortFrequencyDesc {
            get {
                return ResourceManager.GetString("SortFrequencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblik. lastnosti (A-Ž).
        /// </summary>
        public static string SortMsdAsc {
            get {
                return ResourceManager.GetString("SortMsdAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblik. lastnosti (Ž-A).
        /// </summary>
        public static string SortMsdDesc {
            get {
                return ResourceManager.GetString("SortMsdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana oblika (A-Ž).
        /// </summary>
        public static string SortStandardAsc {
            get {
                return ResourceManager.GetString("SortStandardAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana oblika (Ž-A).
        /// </summary>
        public static string SortStandardDesc {
            get {
                return ResourceManager.GetString("SortStandardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana oblika.
        /// </summary>
        public static string StandardForm {
            get {
                return ResourceManager.GetString("StandardForm", resourceCulture);
            }
        }
    }
}
