//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gos.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O viru.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsi viri.
        /// </summary>
        public static string AllSources {
            get {
                return ResourceManager.GetString("AllSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vseeno.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uporabi.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center za jezikovne vire in tehnologije.
        /// </summary>
        public static string Cjvt {
            get {
                return ResourceManager.GetString("Cjvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počisti.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskanje.
        /// </summary>
        public static string Concordance {
            get {
                return ResourceManager.GetString("Concordance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enostavno iskanje.
        /// </summary>
        public static string ConcordanceHint {
            get {
                return ResourceManager.GetString("ConcordanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korpus govorjene slovenščine.
        /// </summary>
        public static string Corpora {
            get {
                return ResourceManager.GetString("Corpora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanal.
        /// </summary>
        public static string DiscourseChannelAggregation {
            get {
                return ResourceManager.GetString("DiscourseChannelAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip govornega dogodka.
        /// </summary>
        public static string DiscourseEventAggregation {
            get {
                return ResourceManager.GetString("DiscourseEventAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regija snemanja.
        /// </summary>
        public static string DiscourseRegionAggregation {
            get {
                return ResourceManager.GetString("DiscourseRegionAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip govora.
        /// </summary>
        public static string DiscourseTypeAggregation {
            get {
                return ResourceManager.GetString("DiscourseTypeAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leto snemanja.
        /// </summary>
        public static string DiscourseYearAggregation {
            get {
                return ResourceManager.GetString("DiscourseYearAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenos vira.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvoz.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvoz podatkov.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prvih.
        /// </summary>
        public static string ExportFirst {
            get {
                return ResourceManager.GetString("ExportFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvoziš lahko največ 1000 zapisov!.
        /// </summary>
        public static string ExportMax {
            get {
                return ResourceManager.GetString("ExportMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naključnih.
        /// </summary>
        public static string ExportRandom {
            get {
                return ResourceManager.GetString("ExportRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zapisov..
        /// </summary>
        public static string ExportRecords {
            get {
                return ResourceManager.GetString("ExportRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Število zapisov je {0}..
        /// </summary>
        public static string ExportTotal {
            get {
                return ResourceManager.GetString("ExportTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvozi.
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najdi.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgodovina iskanj.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgodovina iskanj je prazna!.
        /// </summary>
        public static string HistoryEmpty {
            get {
                return ResourceManager.GetString("HistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o viru.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je.
        /// </summary>
        public static string IsCondition {
            get {
                return ResourceManager.GetString("IsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ni.
        /// </summary>
        public static string IsNotCondition {
            get {
                return ResourceManager.GetString("IsNotCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirana osnovna oblika.
        /// </summary>
        public static string LemmaAggregation {
            get {
                return ResourceManager.GetString("LemmaAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne oblike.
        /// </summary>
        public static string LemmasAlternateSearch {
            get {
                return ResourceManager.GetString("LemmasAlternateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostopnost vira.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delo je dostopno pod licenco.
        /// </summary>
        public static string LicenceInfo {
            get {
                return ResourceManager.GetString("LicenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iskanje po seznamih.
        /// </summary>
        public static string ListHint {
            get {
                return ResourceManager.GetString("ListHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše iskanje ni obrodilo sadov..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besedna vrsta.
        /// </summary>
        public static string PartOfSpeechAggregation {
            get {
                return ResourceManager.GetString("PartOfSpeechAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravljanje vira.
        /// </summary>
        public static string ProvidedBy {
            get {
                return ResourceManager.GetString("ProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starost govorca.
        /// </summary>
        public static string SpeakerAgeAggregation {
            get {
                return ResourceManager.GetString("SpeakerAgeAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izobrazba govorca.
        /// </summary>
        public static string SpeakerEducationAggregation {
            get {
                return ResourceManager.GetString("SpeakerEducationAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvi jezik govorca.
        /// </summary>
        public static string SpeakerLanguageAggregation {
            get {
                return ResourceManager.GetString("SpeakerLanguageAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regija govorca.
        /// </summary>
        public static string SpeakerRegionAggregation {
            get {
                return ResourceManager.GetString("SpeakerRegionAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol govorca.
        /// </summary>
        public static string SpeakerSexAggregation {
            get {
                return ResourceManager.GetString("SpeakerSexAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diskurzov.
        /// </summary>
        public static string StatsDiscourses {
            get {
                return ResourceManager.GetString("StatsDiscourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to izjav.
        /// </summary>
        public static string StatsStatements {
            get {
                return ResourceManager.GetString("StatsStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to besed.
        /// </summary>
        public static string StatsWords {
            get {
                return ResourceManager.GetString("StatsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorni zapis.
        /// </summary>
        public static string TranscriptionTypeConversational {
            get {
                return ResourceManager.GetString("TranscriptionTypeConversational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogovorno.
        /// </summary>
        public static string TranscriptionTypeConversationalShort {
            get {
                return ResourceManager.GetString("TranscriptionTypeConversationalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirani zapis.
        /// </summary>
        public static string TranscriptionTypeStandard {
            get {
                return ResourceManager.GetString("TranscriptionTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardizirano.
        /// </summary>
        public static string TranscriptionTypeStandardShort {
            get {
                return ResourceManager.GetString("TranscriptionTypeStandardShort", resourceCulture);
            }
        }
    }
}
