//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gos.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gos.Web.Resources.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sources.
        /// </summary>
        public static string AllSources {
            get {
                return ResourceManager.GetString("AllSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre for Language Resources and Technologies.
        /// </summary>
        public static string Cjvt {
            get {
                return ResourceManager.GetString("Cjvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Concordance {
            get {
                return ResourceManager.GetString("Concordance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple search.
        /// </summary>
        public static string ConcordanceHint {
            get {
                return ResourceManager.GetString("ConcordanceHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpus of Spoken Slovene.
        /// </summary>
        public static string Corpora {
            get {
                return ResourceManager.GetString("Corpora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string DiscourseChannelAggregation {
            get {
                return ResourceManager.GetString("DiscourseChannelAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        public static string DiscourseEventAggregation {
            get {
                return ResourceManager.GetString("DiscourseEventAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string DiscourseRegionAggregation {
            get {
                return ResourceManager.GetString("DiscourseRegionAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discourse type.
        /// </summary>
        public static string DiscourseTypeAggregation {
            get {
                return ResourceManager.GetString("DiscourseTypeAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string DiscourseYearAggregation {
            get {
                return ResourceManager.GetString("DiscourseYearAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download source.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        public static string ExportFirst {
            get {
                return ResourceManager.GetString("ExportFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can export up to 1000 records!.
        /// </summary>
        public static string ExportMax {
            get {
                return ResourceManager.GetString("ExportMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string ExportRandom {
            get {
                return ResourceManager.GetString("ExportRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to records..
        /// </summary>
        public static string ExportRecords {
            get {
                return ResourceManager.GetString("ExportRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of records is {0}..
        /// </summary>
        public static string ExportTotal {
            get {
                return ResourceManager.GetString("ExportTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search history is empty!.
        /// </summary>
        public static string HistoryEmpty {
            get {
                return ResourceManager.GetString("HistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string IsCondition {
            get {
                return ResourceManager.GetString("IsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string IsNotCondition {
            get {
                return ResourceManager.GetString("IsNotCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardized basic form.
        /// </summary>
        public static string LemmaAggregation {
            get {
                return ResourceManager.GetString("LemmaAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic forms.
        /// </summary>
        public static string LemmasAlternateSearch {
            get {
                return ResourceManager.GetString("LemmasAlternateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work is available under.
        /// </summary>
        public static string LicenceInfo {
            get {
                return ResourceManager.GetString("LicenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List search.
        /// </summary>
        public static string ListHint {
            get {
                return ResourceManager.GetString("ListHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for your search..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of speech.
        /// </summary>
        public static string PartOfSpeechAggregation {
            get {
                return ResourceManager.GetString("PartOfSpeechAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided by.
        /// </summary>
        public static string ProvidedBy {
            get {
                return ResourceManager.GetString("ProvidedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of the speaker.
        /// </summary>
        public static string SpeakerAgeAggregation {
            get {
                return ResourceManager.GetString("SpeakerAgeAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education of the speaker.
        /// </summary>
        public static string SpeakerEducationAggregation {
            get {
                return ResourceManager.GetString("SpeakerEducationAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker&apos;s first language.
        /// </summary>
        public static string SpeakerLanguageAggregation {
            get {
                return ResourceManager.GetString("SpeakerLanguageAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region of the speaker.
        /// </summary>
        public static string SpeakerRegionAggregation {
            get {
                return ResourceManager.GetString("SpeakerRegionAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender of the speaker.
        /// </summary>
        public static string SpeakerSexAggregation {
            get {
                return ResourceManager.GetString("SpeakerSexAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speech events.
        /// </summary>
        public static string StatsDiscourses {
            get {
                return ResourceManager.GetString("StatsDiscourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utterances.
        /// </summary>
        public static string StatsStatements {
            get {
                return ResourceManager.GetString("StatsStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to words.
        /// </summary>
        public static string StatsWords {
            get {
                return ResourceManager.GetString("StatsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation-based spelling.
        /// </summary>
        public static string TranscriptionTypeConversational {
            get {
                return ResourceManager.GetString("TranscriptionTypeConversational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation-based.
        /// </summary>
        public static string TranscriptionTypeConversationalShort {
            get {
                return ResourceManager.GetString("TranscriptionTypeConversationalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardized spelling.
        /// </summary>
        public static string TranscriptionTypeStandard {
            get {
                return ResourceManager.GetString("TranscriptionTypeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardized.
        /// </summary>
        public static string TranscriptionTypeStandardShort {
            get {
                return ResourceManager.GetString("TranscriptionTypeStandardShort", resourceCulture);
            }
        }
    }
}
